### ISSUE TITLE
Testing private routines

### ISSUE THREAD

**Issue by gitporst** [Goddard-Fortran-Ecosystem/pFUnit_demos#5]
I have a derived type with private procedures and would like to test them. However, for testing purposes I need to import them in my test module and thus make them public. Is there any way around that? (https://stackoverflow.com/questions/32849827/how-to-access-private-variables-in-fortran-modules for variables)

**Comment by tclune** [comment]
There are methods, but all have their own downsides.  

The easiest thing of course is to make the entity public and argue that testing is more important than encapsulation.   (The example on stackoverflow is for a setter, which does non really warrant a test, much less a violation of encapsulation.)

The next easiest is to create another "getter" in the module to return that value.   

A 3rd possibility that I often use with module procedures, but should also work with module variables is the following.     I have two modules.   The first has the real content and makes everything that is needed for testing ```PUBLIC```.       I then have a second module that uses the first module but only uses ```PUBLIC``` for the entities that should be public.     I have a convention to name the first module with an "_private" suffix to indicate that external interfaces should not use that module.   (Sort of an ironic notation.   The module is private for the other uses, but needs the ```PUBLIC``` declaration for testing.)

I suppose there are also cheats involving pointers, though I'm not aware of a case where I'd recommend that over just making the entity ```PUBLIC``` in the first place.
 
There is also a more OO advanced approach called dependency injection, but it is not applicable the simpler cases such as your example.   The basic idea is that the test calls your procedure with objects that record what happens to them.   The test can then query the passed object for information.   If the "input" variable were a derived type instead of an integer, and the dummy argument was declared as "CLASS", _and_ you called some method on the "input" variable, then the technique could apply.
